name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        name: Setup Node.js
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Build and test
        run: |
          rm -rf dist
          npx nx run forge:build
          npx nx run forge:test
          npx nx run forge-e2e:e2e
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
